import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import WorkoutProvider from "@/contexts/WorkoutProvider";
import { ToastContainer } from "react-toastify";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const oswald = Oswald({
    variable: "--font-oswald",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={`${inter.variable} ${oswald.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col bg-black">
                <WorkoutProvider>
                    <header>
                        <Navbar></Navbar>
                    </header>
                    <>{children}</>
                    <Footer></Footer>
                </WorkoutProvider>
                <ToastContainer />
            </body>
        </html>
    );
}
